@startuml
title __Transit change detection__ sequence
autonumber
hide footbox

participant "NAP" as NAP
database "NAP DB" as DB

NAP->NAP: Scheduled detection task
activate NAP
  NAP->DB: Query services
  activate DB
  return

  loop For each service
    NAP->DB: Query package ids
    activate DB
    return
    NAP->NAP: Detect changes
    activate NAP
    NAP->DB: Store result
    activate DB
    return
  end

@enduml
