@startuml
title __Transit data import__ sequence
autonumber
hide footbox

participant "NAP" as IMP
database "NAP DB\n" as DB
database "Package archive\n(AWS S3)" as S3
box
boundary "External interface \n" as IFACE
end box

group Import procedure
IMP->DB: Fetch interfaces needing update
return Interfaces to update
    loop For each interface
    IMP->IFACE: Fetch latest package
    return Response: package archive or HTTP 304 Not Modified
        alt New package archive
           IMP->DB: Update package metadata
         alt Kalkati
            IMP->IMP: Convert to GTFS
         end
         IMP->DB: Calculate package hashes
         IMP->S3: Store package archive
         IMP->DB: Store parsed transit service data
        else 304 Not Modified
          IMP->DB: Update package check timestamp
        end
    end
end


@enduml
