@startuml
title __Transit change detection logic__

(*)--> "**0:** Scheduled detection task \n or \n Manually triggered detection task"
--> "1: Query from db \n services for which to run change detection"
partition "2: Prepare input data" {
    --> [ **List of service ids**] "**2a**: Query route hashes from db"
    --> "**2b:** Mark holiday/exception days in input data"
    -->  "Format route vectors"
}

--> [ **List of routes** ] "Iterate list of routes" as a0

partition "3: Find weeks with traffic pattern changes" {
    --> [ **List of weeks** \n for every route, every service] "3a: Analyse remaining weeks" as a1
    --> [ **List of remaining** \n **un-analysed weeks**] "3b: Find next week \n with traffic hash different \n than baseline week, \ntaking rules into account"
    if Unanalysed weeks remaining?
    --> [true] a1
    else
    ' nothing to draw here, go to next step
    endif
}

partition "4: Find days with traffic pattern changes" {
--> [ **Lists of traffic pattern change weeks** \n for every route, every service] "4a: Iterate list of weeks \n of a route" as b1
--> "4b: Fetch from db data \n for trips for days of the week"
    partition "Compare trips of different and baseline day" {
        --> "4c: Compare trips of \n different week's day \n and baseline week's day"
        --> "Find 1st common stop"
        --> "Combine trips \n by stoptime \n and 1st common stop"
        --> "Check time difference \n for each stop in trip pairs"
        --> "Check new or removed \n stops in trip pairs"
        --> "Resolve change summary \n for the analysed day"
        note right: added-trips,\nremoved-trips,\nstop-time-changes,\nstop-seq-changes
    }
    if weeks remaining?
    -left-> [true] b1
    else
    endif
}

partition "5: Store to db" {
    --> "Resolve & Update to db \n next change detection date for service"
    --> "Resolve summary of traffic changes for services\nInsert to db `gtfs-transit-changes` records"
    --> "Resolve summary of traffic changes for routes (of each service) \nInsert to db `detected-route-change` records \nInsert to db `detected-change-history` records"
}
--> (*)

@enduml
