@startuml
title __Transit change detection logic__

(*)--> "Scheduled detection task \n or \n Manually triggered detection task"
--> "1: Query from db \n services for which to run change detection"
partition "2: Query and prepare data" {
    --> [list of service ids] "2a: Query route hashes from db"
    --> "2b: Override holidays in route hashes"
    -->  "Format route vectors"
}

--> [ **list of routes**] "Iterate list of routes" as a0

partition "3: Iterate & analyse: \n weeks of each route" {
    --> [ **list of weeks** \n for every route, every service] "Iterate weeks \n filter remaining weeks" as a1
    --> [list of remaining \n un-analysed weeks] "3b: Find next week \n with traffic changes"
    --> "Detect some change types: \n no-traffic, changed"
    if weeks remaining?
    --> [true] a1
    else
    --> [false] "Detect some change types: \n ending"
    endif
}

partition "4: Iterate & Analyse: \n days of each traffic change week" {
--> [ **list of changed weeks** \n for every route, every service] "4a: Iterate list of weeks \n of a route" as b1
--> "4b: Fetch from db data \n for trips for days of the week"
    partition "Compare trips of different and baseline day" {
        --> "4c: Compare trips of \n different week's day \n and baseline week's day"
        --> "Find 1st common stop"
        --> "Combine trips \n by stoptime \n and 1st common stop"
        --> "Check time difference \n for each stop in trip pairs"
        --> "Check new or removed \n stops in trip pairs"
        --> "Resolve change summary \n for the analysed day"
        note right: added-trips,\nremoved-trips,\nstop-time-changes,\nstop-seq-changes
    }
    if weeks remaining?
    -left-> [true] b1
    else
    endif
}

partition "5: Iterate & Analyse: \n Post-process" {
    --> [false] "Detect some change types: \n added, no-change"
    --> "Resolve final change type"
    --> "Resolve next change detection date"
}

partition "6: Store to db" {
    --> "Insert to db \n analysis for transport service"
    --> "Insert to db \n analysis for every transit change for route"
    --> "Update to db \n transit change history"
}
--> (*)

@enduml
