CREATE TABLE country_list (
    id              SERIAL PRIMARY KEY,
    country_code    CHAR(2) NOT NULL,
    value           VARCHAR(64) NOT NULL,
    locale_code     CHAR(2) NOT NULL);

-- Finnish
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AF', E'Afganistan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AX', E'Ahvenanmaa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NL', E'Alankomaat','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AL', E'Albania','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DZ', E'Algeria','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AS', E'Amerikan Samoa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AD', E'Andorra','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AO', E'Angola','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AI', E'Anguilla','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AQ', E'Antarktis','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AG', E'Antigua ja Barbuda','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AE', E'Arabiemiirikunnat','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AR', E'Argentiina','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AM', E'Armenia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AW', E'Aruba','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AC', E'Ascension-saari','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AU', E'Australia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AZ', E'Azerbaidžan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BS', E'Bahama','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BH', E'Bahrain','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BD', E'Bangladesh','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BB', E'Barbados','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BE', E'Belgia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BZ', E'Belize','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BJ', E'Benin','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BM', E'Bermuda','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BT', E'Bhutan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BO', E'Bolivia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BA', E'Bosnia ja Hertsegovina','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BW', E'Botswana','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BR', E'Brasilia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IO', E'Brittiläinen Intian valtameren alue','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VG', E'Brittiläiset Neitsytsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BN', E'Brunei','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BG', E'Bulgaria','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BF', E'Burkina Faso','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BI', E'Burundi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KY', E'Caymansaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EA', E'Ceuta ja Melilla','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CL', E'Chile','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CK', E'Cookinsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CR', E'Costa Rica','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CW', E'Curaçao','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DG', E'Diego Garcia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DJ', E'Djibouti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DM', E'Dominica','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DO', E'Dominikaaninen tasavalta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EC', E'Ecuador','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EG', E'Egypti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SV', E'El Salvador','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ER', E'Eritrea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ES', E'Espanja','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZA', E'Etelä-Afrikka','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GS', E'Etelä-Georgia ja Eteläiset Sandwichsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KR', E'Etelä-Korea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SS', E'Etelä-Sudan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ET', E'Etiopia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FK', E'Falklandinsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FJ', E'Fidži','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PH', E'Filippiinit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FO', E'Färsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GA', E'Gabon','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GM', E'Gambia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GE', E'Georgia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GH', E'Ghana','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GI', E'Gibraltar','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GD', E'Grenada','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GL', E'Grönlanti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GP', E'Guadeloupe','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GU', E'Guam','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GT', E'Guatemala','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GG', E'Guernsey','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GN', E'Guinea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GW', E'Guinea-Bissau','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GY', E'Guyana','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HT', E'Haiti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HN', E'Honduras','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HK', E'Hongkong – Kiinan e.h.a.','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SJ', E'Huippuvuoret ja Jan Mayen','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ID', E'Indonesia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IN', E'Intia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IQ', E'Irak','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IR', E'Iran','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IE', E'Irlanti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IS', E'Islanti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GB', E'Iso-Britannia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IL', E'Israel','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IT', E'Italia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TL', E'Itä-Timor','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AT', E'Itävalta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JM', E'Jamaika','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JP', E'Japani','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YE', E'Jemen','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JE', E'Jersey','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JO', E'Jordania','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CX', E'Joulusaari','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KH', E'Kambodža','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CM', E'Kamerun','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CA', E'Kanada','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IC', E'Kanariansaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CV', E'Kap Verde','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BQ', E'Karibian Alankomaat','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KZ', E'Kazakstan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KE', E'Kenia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CF', E'Keski-Afrikan tasavalta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CN', E'Kiina','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KG', E'Kirgisia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KI', E'Kiribati','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CO', E'Kolumbia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KM', E'Komorit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CD', E'Kongon demokraattinen tasavalta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CG', E'Kongon tasavalta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CC', E'Kookossaaret (Keelingsaaret)','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XK', E'Kosovo','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GR', E'Kreikka','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HR', E'Kroatia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CU', E'Kuuba','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KW', E'Kuwait','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CY', E'Kypros','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LA', E'Laos','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LV', E'Latvia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LS', E'Lesotho','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LB', E'Libanon','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LR', E'Liberia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LY', E'Libya','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LI', E'Liechtenstein','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LT', E'Liettua','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LU', E'Luxemburg','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EH', E'Länsi-Sahara','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MO', E'Macao – Kiinan e.h.a.','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MG', E'Madagaskar','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MW', E'Malawi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MV', E'Malediivit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MY', E'Malesia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ML', E'Mali','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MT', E'Malta','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IM', E'Mansaari','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MA', E'Marokko','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MH', E'Marshallinsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MQ', E'Martinique','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MR', E'Mauritania','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MU', E'Mauritius','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YT', E'Mayotte','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MX', E'Meksiko','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FM', E'Mikronesian liittovaltio','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MD', E'Moldova','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MC', E'Monaco','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MN', E'Mongolia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ME', E'Montenegro','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MS', E'Montserrat','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MZ', E'Mosambik','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MM', E'Myanmar (Burma)','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NA', E'Namibia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NR', E'Nauru','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NP', E'Nepal','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NI', E'Nicaragua','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NE', E'Niger','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NG', E'Nigeria','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NU', E'Niue','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NF', E'Norfolkinsaari','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NO', E'Norja','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CI', E'Norsunluurannikko','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'OM', E'Oman','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PK', E'Pakistan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PW', E'Palau','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PS', E'Palestiinalaisalueet','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PA', E'Panama','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PG', E'Papua-Uusi-Guinea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PY', E'Paraguay','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PE', E'Peru','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PN', E'Pitcairn','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KP', E'Pohjois-Korea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MK', E'Pohjois-Makedonia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MP', E'Pohjois-Mariaanit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PT', E'Portugali','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XA', E'Pseudo-Accents','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XB', E'Pseudo-Bidi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PR', E'Puerto Rico','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PL', E'Puola','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GQ', E'Päiväntasaajan Guinea','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'QA', E'Qatar','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FR', E'Ranska','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TF', E'Ranskan eteläiset alueet','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GF', E'Ranskan Guayana','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PF', E'Ranskan Polynesia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RE', E'Réunion','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RO', E'Romania','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RW', E'Ruanda','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SE', E'Ruotsi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SH', E'Saint Helena','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KN', E'Saint Kitts ja Nevis','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LC', E'Saint Lucia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VC', E'Saint Vincent ja Grenadiinit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BL', E'Saint-Barthélemy','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MF', E'Saint-Martin','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PM', E'Saint-Pierre ja Miquelon','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DE', E'Saksa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SB', E'Salomonsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZM', E'Sambia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WS', E'Samoa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SM', E'San Marino','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ST', E'São Tomé ja Príncipe','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SA', E'Saudi-Arabia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SN', E'Senegal','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RS', E'Serbia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SC', E'Seychellit','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SL', E'Sierra Leone','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SG', E'Singapore','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SX', E'Sint Maarten','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SK', E'Slovakia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SI', E'Slovenia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SO', E'Somalia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LK', E'Sri Lanka','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SD', E'Sudan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FI', E'Suomi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SR', E'Suriname','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CH', E'Sveitsi','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SZ', E'Swazimaa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SY', E'Syyria','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TJ', E'Tadžikistan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TW', E'Taiwan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TZ', E'Tansania','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DK', E'Tanska','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TH', E'Thaimaa','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TG', E'Togo','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TK', E'Tokelau','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TO', E'Tonga','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TT', E'Trinidad ja Tobago','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TA', E'Tristan da Cunha','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TD', E'Tšad','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CZ', E'Tšekki','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TN', E'Tunisia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TR', E'Turkki','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TM', E'Turkmenistan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TC', E'Turks- ja Caicossaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TV', E'Tuvalu','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UG', E'Uganda','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UA', E'Ukraina','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HU', E'Unkari','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UY', E'Uruguay','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NC', E'Uusi-Kaledonia','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NZ', E'Uusi-Seelanti','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UZ', E'Uzbekistan','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BY', E'Valko-Venäjä','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VU', E'Vanuatu','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VA', E'Vatikaani','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VE', E'Venezuela','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RU', E'Venäjä','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VN', E'Vietnam','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EE', E'Viro','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WF', E'Wallis ja Futuna','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'US', E'Yhdysvallat','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UM', E'Yhdysvaltain erillissaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VI', E'Yhdysvaltain Neitsytsaaret','FI');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZW', E'Zimbabwe','FI');

-- Swedish
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AF', E'Afghanistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AL', E'Albánia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DZ', E'Algeria','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'US', E'Amerihká ovttastuvvan stáhtat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AS', E'Amerihká Samoa','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AD', E'Andorra','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AO', E'Angola','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AI', E'Anguilla','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AQ', E'Antárktis','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AG', E'Antigua ja Barbuda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VI', E'AOS Virgin-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AR', E'Argentina','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AM', E'Armenia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AW', E'Aruba','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AC', E'Ascension','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AZ', E'Aserbaižan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AU', E'Austrália','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BS', E'Bahamas','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BH', E'Bahrain','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BD', E'Bangladesh','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BB', E'Barbados','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BE', E'Belgia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BZ', E'Belize','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BJ', E'Benin','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BM', E'Bermuda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BT', E'Bhutan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BO', E'Bolivia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BA', E'Bosnia-Hercegovina','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BW', E'Botswana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BR', E'Brasil','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IO', E'British Indian Ocean Territory','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VG', E'Brittania Virgin-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BN', E'Brunei','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BG', E'Bulgária','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BF', E'Burkina Faso','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MM', E'Burma','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BI', E'Burundi','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BQ', E'Caribbean Netherlands','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KY', E'Cayman-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EA', E'Ceuta ja Melilla','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CC', E'Cocos-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CK', E'Cook-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CR', E'Costa Rica','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CW', E'Curaçao','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CZ', E'Čeahkka','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CL', E'Čiile','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KP', E'Davvi-Korea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MP', E'Davvi-Mariánat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SD', E'Davvisudan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DK', E'Dánmárku','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DG', E'Diego Garcia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DJ', E'Djibouti','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DM', E'Dominica','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DO', E'Dominikána dásseváldi','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DE', E'Duiska','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TR', E'Durka','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EC', E'Ecuador','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EG', E'Egypta','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GQ', E'Ekvatoriála Guinea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SV', E'El Salvador','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CI', E'Elfenbenariddu','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ER', E'Eritrea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EE', E'Estlánda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ET', E'Etiopia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FK', E'Falklandsullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FO', E'Fearsullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FJ', E'Fijisullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PH', E'Filippiinnat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FR', E'Frankriika','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GF', E'Frankriikka Guayana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PF', E'Frankriikka Polynesia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MF', E'Frankriikka Saint Martin','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TF', E'French Southern Territories','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GA', E'Gabon','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CF', E'Gaska-Afrihká dásseváldi','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GM', E'Gámbia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GE', E'Georgia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GH', E'Ghana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GI', E'Gibraltar','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GR', E'Greika','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GD', E'Grenada','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GP', E'Guadeloupe','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GU', E'Guam','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GT', E'Guatemala','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GG', E'Guernsey','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GN', E'Guinea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GW', E'Guinea-Bissau','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GY', E'Guyana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HT', E'Haiti','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HN', E'Honduras','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HK', E'Hongkong','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IN', E'India','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ID', E'Indonesia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IQ', E'Irak','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IR', E'Iran','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IE', E'Irlánda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IS', E'Islánda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IL', E'Israel','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IT', E'Itália','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JM', E'Jamaica','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JP', E'Japána','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YE', E'Jemen','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JE', E'Jersey','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JO', E'Jordánia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CX', E'Juovllat-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GL', E'Kalaallit Nunaat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KH', E'Kambodža','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CM', E'Kamerun','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CA', E'Kanáda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IC', E'Kanáriasullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CV', E'Kap Verde','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KZ', E'Kasakstan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KE', E'Kenia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CN', E'Kiinná','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KG', E'Kirgisistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KI', E'Kiribati','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CO', E'Kolombia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KM', E'Komoros','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CG', E'Kongo-Brazzaville','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CD', E'Kongo-Kinshasa','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XK', E'Kosovo','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HR', E'Kroátia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CU', E'Kuba','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KW', E'Kuwait','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CY', E'Kypros','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LA', E'Laos','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LV', E'Látvia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LS', E'Lesotho','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LB', E'Libanon','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LR', E'Liberia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LY', E'Libya','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LI', E'Liechtenstein','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LT', E'Lietuva','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GS', E'Lulli Georgia ja Lulli Sandwich-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LU', E'Luxembourg','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MG', E'Madagaskar','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MO', E'Makáo','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MK', E'Makedonia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MW', E'Malawi','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MV', E'Malediivvat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MY', E'Malesia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ML', E'Mali','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IM', E'Mann-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MA', E'Marokko','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MH', E'Marshallsullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MQ', E'Martinique','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MR', E'Mauretánia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MU', E'Mauritius','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YT', E'Mayotte','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MT', E'Málta','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZA', E'Mátta-Afrihká','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KR', E'Mátta-Korea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SS', E'Máttasudan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MX', E'Meksiko','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FM', E'Mikronesia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MD', E'Moldávia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MC', E'Monaco','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MN', E'Mongolia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ME', E'Montenegro','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MS', E'Montserrat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MZ', E'Mosambik','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NA', E'Namibia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NR', E'Nauru','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NP', E'Nepal','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NI', E'Nicaragua','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NE', E'Niger','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NG', E'Nigeria','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NU', E'Niue','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NF', E'Norfolksullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NO', E'Norga','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TL', E'Nuorta-Timor','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AT', E'Nuortariika','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EH', E'Oarje-Sahára','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NC', E'Ođđa-Kaledonia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NZ', E'Ođđa-Selánda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'OM', E'Oman','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AE', E'Ovttastuvvan Arábaemiráhtat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PK', E'Pakistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PW', E'Palau','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PS', E'Palestina','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PA', E'Panama','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PG', E'Papua-Ođđa-Guinea','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PY', E'Paraguay','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PE', E'Peru','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PN', E'Pitcairn','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PL', E'Polen','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PT', E'Portugála','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XA', E'Pseudo-Accents','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XB', E'Pseudo-Bidi','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PR', E'Puerto Rico','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'QA', E'Qatar','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RE', E'Réunion','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RO', E'Románia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RU', E'Ruošša','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SE', E'Ruoŧŧa','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RW', E'Rwanda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BL', E'Saint Barthélemy','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SH', E'Saint Helena','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KN', E'Saint Kitts ja Nevis','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LC', E'Saint Lucia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PM', E'Saint Pierre ja Miquelon','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VC', E'Saint Vincent ja Grenadine','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SB', E'Salomon-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WS', E'Samoa','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SM', E'San Marino','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SA', E'Saudi-Arábia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SN', E'Senegal','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RS', E'Serbia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SC', E'Seychellsullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SL', E'Sierra Leone','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SG', E'Singapore','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SK', E'Slovákia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SI', E'Slovenia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SO', E'Somália','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ES', E'Spánia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LK', E'Sri Lanka','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GB', E'Stuorra-Británnia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FI', E'Suopma','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SR', E'Surinam','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SJ', E'Svalbárda ja Jan Mayen','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SZ', E'Svazieana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SY', E'Syria','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ST', E'São Tomé ja Príncipe','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CH', E'Šveica','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TW', E'Taiwan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TZ', E'Tanzánia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TJ', E'Tažikistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TD', E'Tčad','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TH', E'Thaieana','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TG', E'Togo','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TK', E'Tokelau','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TO', E'Tonga','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TT', E'Trinidad ja Tobago','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TA', E'Tristan da Cunha','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TN', E'Tunisia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TM', E'Turkmenistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TC', E'Turks ja Caicos-sullot','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TV', E'Tuvalu','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UM', E'U.S. Outlying Islands','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UG', E'Uganda','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UA', E'Ukraina','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HU', E'Ungár','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UY', E'Uruguay','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UZ', E'Usbekistan','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VU', E'Vanuatu','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VA', E'Vatikána','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VE', E'Venezuela','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VN', E'Vietnam','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BY', E'Vilges-Ruošša','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NL', E'Vuolleeatnamat','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SX', E'Vuolleeatnamat Saint Martin','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WF', E'Wallis ja Futuna','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZM', E'Zambia','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZW', E'Zimbabwe','SV');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AX', E'Ålánda','SV');

-- English

INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AF', E'Afghanistan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AX', E'Åland Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AL', E'Albania','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DZ', E'Algeria','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AS', E'American Samoa','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AD', E'Andorra','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AO', E'Angola','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AI', E'Anguilla','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AQ', E'Antarctica','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AG', E'Antigua & Barbuda','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AR', E'Argentina','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AM', E'Armenia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AW', E'Aruba','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AC', E'Ascension Island','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AU', E'Australia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AT', E'Austria','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AZ', E'Azerbaijan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BS', E'Bahamas','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BH', E'Bahrain','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BD', E'Bangladesh','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BB', E'Barbados','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BY', E'Belarus','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BE', E'Belgium','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BZ', E'Belize','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BJ', E'Benin','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BM', E'Bermuda','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BT', E'Bhutan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BO', E'Bolivia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BA', E'Bosnia & Herzegovina','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BW', E'Botswana','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BR', E'Brazil','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IO', E'British Indian Ocean Territory','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VG', E'British Virgin Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BN', E'Brunei','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BG', E'Bulgaria','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BF', E'Burkina Faso','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BI', E'Burundi','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KH', E'Cambodia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CM', E'Cameroon','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CA', E'Canada','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IC', E'Canary Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CV', E'Cape Verde','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BQ', E'Caribbean Netherlands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KY', E'Cayman Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CF', E'Central African Republic','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EA', E'Ceuta & Melilla','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TD', E'Chad','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CL', E'Chile','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CN', E'China','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CX', E'Christmas Island','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CC', E'Cocos (Keeling) Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CO', E'Colombia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KM', E'Comoros','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CG', E'Congo - Brazzaville','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CD', E'Congo - Kinshasa','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CK', E'Cook Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CR', E'Costa Rica','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CI', E'Côte d’Ivoire','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HR', E'Croatia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CU', E'Cuba','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CW', E'Curaçao','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CY', E'Cyprus','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CZ', E'Czechia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DK', E'Denmark','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DG', E'Diego Garcia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DJ', E'Djibouti','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DM', E'Dominica','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DO', E'Dominican Republic','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EC', E'Ecuador','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EG', E'Egypt','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SV', E'El Salvador','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GQ', E'Equatorial Guinea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ER', E'Eritrea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EE', E'Estonia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SZ', E'Eswatini','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ET', E'Ethiopia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FK', E'Falkland Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FO', E'Faroe Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FJ', E'Fiji','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FI', E'Finland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FR', E'France','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GF', E'French Guiana','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PF', E'French Polynesia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TF', E'French Southern Territories','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GA', E'Gabon','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GM', E'Gambia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GE', E'Georgia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'DE', E'Germany','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GH', E'Ghana','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GI', E'Gibraltar','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GR', E'Greece','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GL', E'Greenland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GD', E'Grenada','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GP', E'Guadeloupe','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GU', E'Guam','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GT', E'Guatemala','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GG', E'Guernsey','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GN', E'Guinea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GW', E'Guinea-Bissau','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GY', E'Guyana','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HT', E'Haiti','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HN', E'Honduras','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HK', E'Hong Kong SAR China','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'HU', E'Hungary','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IS', E'Iceland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IN', E'India','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ID', E'Indonesia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IR', E'Iran','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IQ', E'Iraq','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IE', E'Ireland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IM', E'Isle of Man','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IL', E'Israel','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'IT', E'Italy','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JM', E'Jamaica','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JP', E'Japan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JE', E'Jersey','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'JO', E'Jordan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KZ', E'Kazakhstan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KE', E'Kenya','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KI', E'Kiribati','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XK', E'Kosovo','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KW', E'Kuwait','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KG', E'Kyrgyzstan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LA', E'Laos','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LV', E'Latvia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LB', E'Lebanon','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LS', E'Lesotho','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LR', E'Liberia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LY', E'Libya','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LI', E'Liechtenstein','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LT', E'Lithuania','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LU', E'Luxembourg','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MO', E'Macao SAR China','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MG', E'Madagascar','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MW', E'Malawi','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MY', E'Malaysia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MV', E'Maldives','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ML', E'Mali','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MT', E'Malta','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MH', E'Marshall Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MQ', E'Martinique','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MR', E'Mauritania','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MU', E'Mauritius','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YT', E'Mayotte','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MX', E'Mexico','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'FM', E'Micronesia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MD', E'Moldova','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MC', E'Monaco','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MN', E'Mongolia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ME', E'Montenegro','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MS', E'Montserrat','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MA', E'Morocco','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MZ', E'Mozambique','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MM', E'Myanmar (Burma)','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NA', E'Namibia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NR', E'Nauru','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NP', E'Nepal','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NL', E'Netherlands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NC', E'New Caledonia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NZ', E'New Zealand','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NI', E'Nicaragua','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NE', E'Niger','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NG', E'Nigeria','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NU', E'Niue','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NF', E'Norfolk Island','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KP', E'North Korea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MK', E'North Macedonia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MP', E'Northern Mariana Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'NO', E'Norway','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'OM', E'Oman','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PK', E'Pakistan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PW', E'Palau','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PS', E'Palestinian Territories','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PA', E'Panama','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PG', E'Papua New Guinea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PY', E'Paraguay','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PE', E'Peru','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PH', E'Philippines','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PN', E'Pitcairn Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PL', E'Poland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PT', E'Portugal','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XA', E'Pseudo-Accents','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'XB', E'Pseudo-Bidi','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PR', E'Puerto Rico','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'QA', E'Qatar','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RE', E'Réunion','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RO', E'Romania','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RU', E'Russia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RW', E'Rwanda','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WS', E'Samoa','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SM', E'San Marino','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ST', E'São Tomé & Príncipe','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SA', E'Saudi Arabia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SN', E'Senegal','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'RS', E'Serbia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SC', E'Seychelles','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SL', E'Sierra Leone','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SG', E'Singapore','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SX', E'Sint Maarten','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SK', E'Slovakia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SI', E'Slovenia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SB', E'Solomon Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SO', E'Somalia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZA', E'South Africa','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GS', E'South Georgia & South Sandwich Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KR', E'South Korea','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SS', E'South Sudan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ES', E'Spain','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LK', E'Sri Lanka','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'BL', E'St Barthélemy','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SH', E'St Helena','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'KN', E'St Kitts & Nevis','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'LC', E'St Lucia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'MF', E'St Martin','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'PM', E'St Pierre & Miquelon','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VC', E'St Vincent & Grenadines','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SD', E'Sudan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SR', E'Suriname','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SJ', E'Svalbard & Jan Mayen','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SE', E'Sweden','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'CH', E'Switzerland','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'SY', E'Syria','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TW', E'Taiwan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TJ', E'Tajikistan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TZ', E'Tanzania','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TH', E'Thailand','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TL', E'Timor-Leste','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TG', E'Togo','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TK', E'Tokelau','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TO', E'Tonga','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TT', E'Trinidad & Tobago','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TA', E'Tristan da Cunha','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TN', E'Tunisia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TR', E'Turkey','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TM', E'Turkmenistan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TC', E'Turks & Caicos Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'TV', E'Tuvalu','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UG', E'Uganda','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UA', E'Ukraine','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'AE', E'United Arab Emirates','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'GB', E'United Kingdom','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'US', E'United States','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UY', E'Uruguay','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UM', E'US Outlying Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VI', E'US Virgin Islands','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'UZ', E'Uzbekistan','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VU', E'Vanuatu','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VA', E'Vatican City','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VE', E'Venezuela','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'VN', E'Vietnam','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'WF', E'Wallis & Futuna','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'EH', E'Western Sahara','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'YE', E'Yemen','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZM', E'Zambia','EN');
INSERT INTO "country_list" ("country_code", "value", "locale_code") VALUES (E'ZW', E'Zimbabwe','EN');
