-- Update country codes to correct ISO 3166-1 form.
-- Remove duplicate Indian Ocean Territories
-- Update Yhdistynyt Kuningaskunta to Iso-Britannia

delete from country where nameeng = 'Indian Ocean Territories';

update country set code = 'AE' where nameeng = 'United Arab Emirates';
update country set code = 'AG' where nameeng = 'Antigua and Barbuda';
update country set code = 'AM' where nameeng = 'Armenia';
update country set code = 'AO' where nameeng = 'Angola';
update country set code = 'AQ' where nameeng = 'Antarctica';
update country set code = 'AR' where nameeng = 'Argentina';
update country set code = 'AT' where nameeng = 'Austria';
update country set code = 'AU' where nameeng = 'Australia';
update country set code = 'BB' where nameeng = 'Barbados';
update country set code = 'BD' where nameeng = 'Bangladesh';
update country set code = 'BE' where nameeng = 'Belgium';
update country set code = 'BG' where nameeng = 'Bulgaria';
update country set code = 'BH' where nameeng = 'Bahrain';
update country set code = 'BA' where nameeng = 'Bosnia and Herzegovina';
update country set code = 'BI' where nameeng = 'Burundi';
update country set code = 'BJ' where nameeng = 'Benin';
update country set code = 'BN' where nameeng = 'Brunei';
update country set code = 'BR' where nameeng = 'Brazil';
update country set code = 'BS' where nameeng = 'The Bahamas';
update country set code = 'BY' where nameeng = 'Belarus';
update country set code = 'BZ' where nameeng = 'Belize';
update country set code = 'CA' where nameeng = 'Canada';
update country set code = 'CD' where nameeng = 'Democratic Republic of the Congo';
update country set code = 'CF' where nameeng = 'Central African Republic';
update country set code = 'CG' where nameeng = 'Republic of the Congo';
update country set code = 'CH' where nameeng = 'Switzerland';
update country set code = 'CK' where nameeng = 'Cook Islands';
update country set code = 'CL' where nameeng = 'Chile';
update country set code = 'CN' where nameeng = 'China';
update country set code = 'CO' where nameeng = 'Colombia';
update country set code = 'CU' where nameeng = 'Cuba';
update country set code = 'CW' where nameeng = 'Curaçao';
update country set code = 'EE' where nameeng = 'Estonia';
update country set code = 'EH' where nameeng = 'Western Sahara';
update country set code = 'ES' where nameeng = 'Spain';
update country set code = 'FO' where nameeng = 'Faroe Islands';
update country set code = 'FR' where nameeng = 'France';
update country set code = 'GD' where nameeng = 'Grenada';
update country set code = 'GI' where nameeng = 'Gibraltar';
update country set code = 'GL' where nameeng = 'Greenland';
update country set code = 'GN' where nameeng = 'Guinea';
Update country set code = 'GQ' where nameeng = 'Equatorial Guinea';
update country set code = 'GR' where nameeng = 'Greece';
update country set code = 'GU' where nameeng = 'Guam';
update country set code = 'GW' where nameeng = 'Guinea-Bissau';
update country set code = 'GY' where nameeng = 'Guyana';
update country set code = 'IE' where nameeng = 'Ireland';
update country set code = 'IL' where nameeng = 'Israel';
update country set code = 'IO' where nameeng = 'British Indian Ocean Territory';
update country set code = 'IQ' where nameeng = 'Iraq';
update country set code = 'IR' where nameeng = 'Iran';
update country set code = 'IS' where nameeng = 'Iceland';
update country set code = 'KM' where nameeng = 'Comoros';
update country set code = 'KP' where nameeng = 'North Korea';
update country set code = 'LB' where nameeng = 'Lebanon';
update country set code = 'LR' where nameeng = 'Liberia';
update country set code = 'LY' where nameeng = 'Libya';
update country set code = 'MA' where nameeng = 'Morocco';
update country set code = 'MD' where nameeng = 'Moldova';
update country set code = 'ME' where nameeng = 'Montenegro';
update country set code = 'MF' where nameeng = 'Saint Martin';
update country set code = 'MG' where nameeng = 'Madagascar';
update country set code = 'ML' where nameeng = 'Mali';
update country set code = 'MN' where nameeng = 'Mongolia';
update country set code = 'MO' where nameeng = 'Macao S.A.R';
update country set code = 'MP' where nameeng = 'Northern Mariana Islands';
update country set code = 'MT' where nameeng = 'Malta';
update country set code = 'MV' where nameeng = 'Maldives';
update country set code = 'MX' where nameeng = 'Mexico';
update country set code = 'MZ' where nameeng = 'Mozambique';
update country set code = 'NI' where nameeng = 'Nicaragua';
update country set code = 'NU' where nameeng = 'Niue';
update country set code = 'PA' where nameeng = 'Panama';
update country set code = 'PF' where nameeng = 'French Polynesia';
update country set code = 'PK' where nameeng = 'Pakistan';
update country set code = 'PR' where nameeng = 'Puerto Rico';
update country set code = 'PT' where nameeng = 'Portugal';
update country set code = 'PY' where nameeng = 'Paraguay';
update country set code = 'SB' where nameeng = 'Solomon Islands';
update country set code = 'SC' where nameeng = 'Seychelles';
update country set code = 'SE' where nameeng = 'Sweden';
update country set code = 'SI' where nameeng = 'Slovenia';
update country set code = 'SK' where nameeng = 'Slovakia';
update country set code = 'SL' where nameeng = 'Sierra Leone';
update country set code = 'SN' where nameeng = 'Senegal';
update country set code = 'SV' where nameeng = 'El Salvador';
update country set code = 'SY' where nameeng = 'Syria';
update country set code = 'SZ' where nameeng = 'Swaziland';
update country set code = 'TC' where nameeng = 'Turks and Caicos Islands';
update country set code = 'TD' where nameeng = 'Chad';
update country set code = 'TN' where nameeng = 'Tunisia';
update country set code = 'TR' where nameeng = 'Turkey';
update country set code = 'TV' where nameeng = 'Tuvalu';

update country set namefin = 'Iso-Britannia', nameswe = 'Storbritannien' where nameeng = 'United Kingdom';
