@startuml
title NeTEx conversion sequenced diagram
autonumber
hide footbox

actor "USER" as USER
participant "NAP" as NAP
database "S3" as S3
database "NAP DB" as DB
participant "ote.netex.netex" as CONVERTER
box <<process>>
participant "Firejail" as FJ
participant "mobi.chouette.command.jar" as CHOUETTE
end box

activate NAP

NAP -> NAP : Scheduled GTFS download
NAP -> CONVERTER : GTFS->PreProcess
activate CONVERTER
return Return changed gtfs.zip
NAP -> CONVERTER : GTFS->NeTEx conversion
activate CONVERTER
CONVERTER->FJ: Call converter using Firejail
activate FJ
FJ->CHOUETTE: Invoke choutette.sh shell script (gtfs.zip, inputGtfs.json, outputNetex.json)
activate CHOUETTE
return Return process exit info
return Return process exit info
CONVERTER->CONVERTER : PostProcess netex.zip
CONVERTER->CONVERTER : Parse process exit info and file system output files
CONVERTER->S3 : Save netex.zip
CONVERTER->DB : Store conversion status metadata
return Return process exit info

@enduml
