@startuml
title NeTEx use-case overview diagram
'autonumber
hide footbox

actor "USER" as USER
actor "ADMIN" as ADMIN
participant "NAP" as NAP
participant "TIS VACO" as CONVERTER

group Conversion task submission
NAP->CONVERTER : Submit GTFS external interfaces
CONVERTER-->NAP: task submission confirmation
end

group Conversion status polling
NAP->CONVERTER : poll task completion
CONVERTER-->NAP: conversion status
end

USER->NAP : Open service viewer
return  Include NeTEx package link

ADMIN -> NAP : Open Admin panel
return Include NeTEx creation status

@enduml
